### ISSUE TITLE
Bugs computing hash tree root in `BuilderBid`

### ISSUE THREAD

**Issue by ralexstokes** [protolambda/mergemock#41]
When I use `mergemock` to compute the hash tree root of a `BuilderBid`, I get some errors:

1) incorrect hash tree root of the `U256Str` type (e.g. in the `BaseFeePerGas` field in the `ExecutionPayloadHeader` type)
2) incorrect hash tree root of the `ExtraData` field of the `ExecutionPayloadHeader` type

(1) is incorrect bc it stores a big int value as bytes in big-endian order -- this is convenient for the textual serialization but there already exists an SSZ implementation for `[32]byte` (the underlying type) which takes the bytes as-is... after trying some things to fix locally, I'd suggest we just use the `Uint256View` from `ztyp`: https://github.com/protolambda/ztyp/blob/master/view/u256.go

Note: this bug likely applies to any use of `U256Str` including the `bid.value`, etc.

(2) I haven't looked into the cause here but suspect an issue with `fastssz` either with serializing the byte list or mixing in the bound in the correct way...

**Comment by metachris** [comment]
Thanks! Could you share some test inputs and expected outputs? Then we could easily add some tests for these.

re 1: sounds good to me to use `ztyp/u256` 👍 

sidenote re 2 - the issue with `ExtraData` might be because mergemock uses a variable length type (`hexutil.Bytes`) so the resulting blockhash matches the blockhash from the execution layer (the [go-ethereum `Header` definition](https://github.com/ethereum/go-ethereum/blob/master/core/types/block.go#L83) uses `[]byte` too). But the [consensus-specs](https://github.com/ethereum/consensus-specs/blob/dev/specs/bellatrix/beacon-chain.md#executionpayloadheader) uses a fixed length byte array (`extra_data: ByteList[MAX_EXTRA_DATA_BYTES]`, `MAX_EXTRA_DATA_BYTES = 32` for bellatrix).

**Comment by protolambda** [comment]
`ByteList` is not fixed length, but has a length *up to* that list-limit. For fixed list types the specs use `Vector`.

**Comment by ralexstokes** [comment]
sounds like @lightclient is debugging this stuff so I'll pause this for now

**Comment by ralexstokes** [comment]
I'll assume this was fixed in #43.
